# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-22 12:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='', max_length=50)),
                ('hometown', models.CharField(default='', max_length=100)),
                ('dateofbirth', models.DateField(default=datetime.date.today)),
                ('coach', models.CharField(default='', max_length=50)),
                ('staff', models.CharField(default='', max_length=50)),
                ('training_base', models.CharField(default='', max_length=100)),
                ('international_debute', models.CharField(default='', max_length=100)),
                ('short_term_goal', models.CharField(default='', max_length=100)),
                ('long_term_goal', models.CharField(default='', max_length=100)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
